server:
  port: 9020
spring:
  application:
    name: order-server
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.1.9:3306/royalmall_oms
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
