server:
  port: 9040
spring:
  application:
    name: storage-server
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.1.9:3306/royalmall_wms
mybatis-plus:
  global-config:
    db-config:
      id-type: auto